//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRASHAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VCSGEntities : DbContext
    {
        public VCSGEntities()
            : base("name=VCSGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vw_PQT_Persons> vw_PQT_Persons { get; set; }
        public DbSet<vw_PQT_Units> vw_PQT_Units { get; set; }
        public DbSet<REFCITYCODE> REFCITYCODEs { get; set; }
        public DbSet<REFCOUNTYCODE> REFCOUNTYCODEs { get; set; }
        public DbSet<vw_PQT_AccidentHeader> vw_PQT_AccidentHeader { get; set; }
    }
}
