//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRASHAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReferenceEntities : DbContext
    {
        public ReferenceEntities()
            : base("name=ReferenceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<REFACCESSCONTROL> REFACCESSCONTROLs { get; set; }
        public DbSet<REFADMINCLASS> REFADMINCLASSes { get; set; }
        public DbSet<REFALCOHOLTEST> REFALCOHOLTESTs { get; set; }
        public DbSet<REFAPPARANTOPCOND> REFAPPARANTOPCONDs { get; set; }
        public DbSet<REFCARGOBODYTYPE> REFCARGOBODYTYPEs { get; set; }
        public DbSet<REFCENSUSCATEGORY> REFCENSUSCATEGORies { get; set; }
        public DbSet<REFCITYCODE> REFCITYCODEs { get; set; }
        public DbSet<REFCLASS1TOWNHIGHWAYS> REFCLASS1TOWNHIGHWAYS { get; set; }
        public DbSet<REFCLOSEYEAR> REFCLOSEYEARs { get; set; }
        public DbSet<REFCONTRIBCIRCUMSTANCE> REFCONTRIBCIRCUMSTANCES { get; set; }
        public DbSet<REFCOUNTYCODE> REFCOUNTYCODEs { get; set; }
        public DbSet<REFCRASHTYPE> REFCRASHTYPEs { get; set; }
        public DbSet<REFDEFECTIVEEQUIPMENT> REFDEFECTIVEEQUIPMENTs { get; set; }
        public DbSet<REFDIRECTION> REFDIRECTIONs { get; set; }
        public DbSet<REFDIROFCOLLISION> REFDIROFCOLLISIONs { get; set; }
        public DbSet<REFDISTANCETYPE> REFDISTANCETYPEs { get; set; }
        public DbSet<REFDOMAINNAME> REFDOMAINNAMEs { get; set; }
        public DbSet<REFDRUGTEST> REFDRUGTESTs { get; set; }
        public DbSet<REFDRUGTESTRESULT> REFDRUGTESTRESULTs { get; set; }
        public DbSet<REFEJECTED> REFEJECTEDs { get; set; }
        public DbSet<REFEMSAGENCy> REFEMSAGENCIES { get; set; }
        public DbSet<REFEQUIPMENTAR> REFEQUIPMENTARS { get; set; }
        public DbSet<REFFASYSDESIGNWAY> REFFASYSDESIGNWAYs { get; set; }
        public DbSet<REFFASYSTRAVELWAY> REFFASYSTRAVELWAYs { get; set; }
        public DbSet<REFFAUAREA> REFFAUAREAs { get; set; }
        public DbSet<REFFIVEYRIMPROVEMENT> REFFIVEYRIMPROVEMENTS { get; set; }
        public DbSet<REFFUNCTCLASS> REFFUNCTCLASSes { get; set; }
        public DbSet<REFGOVLEVOFCTR> REFGOVLEVOFCTRs { get; set; }
        public DbSet<RefGVWROrGCWR> RefGVWROrGCWRs { get; set; }
        public DbSet<REFHIGHWAYDISTRICT> REFHIGHWAYDISTRICTs { get; set; }
        public DbSet<REFHOSPITAL> REFHOSPITALS { get; set; }
        public DbSet<RefImageType> RefImageTypes { get; set; }
        public DbSet<REFINJURY> REFINJURies { get; set; }
        public DbSet<REFINSURANCECO> REFINSURANCECOes { get; set; }
        public DbSet<REFINTERSTATEROUTE> REFINTERSTATEROUTES { get; set; }
        public DbSet<REFINVENRTNUM> REFINVENRTNUMs { get; set; }
        public DbSet<REFLENGTHUNIT> REFLENGTHUNITS { get; set; }
        public DbSet<REFLICENSECLASS> REFLICENSECLASSes { get; set; }
        public DbSet<REFLICRESTRICTPERMISS> REFLICRESTRICTPERMISSes { get; set; }
        public DbSet<REFLIGHT> REFLIGHTs { get; set; }
        public DbSet<REFLRSROUTEMILEAGE> REFLRSROUTEMILEAGEs { get; set; }
        public DbSet<REFLRSROUTENUMBER> REFLRSROUTENUMBERS { get; set; }
        public DbSet<REFMEDIANTYPE> REFMEDIANTYPEs { get; set; }
        public DbSet<REFMILEPTIND> REFMILEPTINDs { get; set; }
        public DbSet<REFMUNICIPALITY> REFMUNICIPALITies { get; set; }
        public DbSet<REFPARKWAYTRUCK> REFPARKWAYTRUCKS { get; set; }
        public DbSet<REFPAVEMENTTYPE> REFPAVEMENTTYPEs { get; set; }
        public DbSet<REFPEDESTRIANCYCLEACTION> REFPEDESTRIANCYCLEACTIONs { get; set; }
        public DbSet<REFPEDESTRIANCYCLELOCATION> REFPEDESTRIANCYCLELOCATIONs { get; set; }
        public DbSet<RefPerceivedRace> RefPerceivedRaces { get; set; }
        public DbSet<REFPERSONTYPE> REFPERSONTYPEs { get; set; }
        public DbSet<REFPLATETYPE> REFPLATETYPEs { get; set; }
        public DbSet<REFPOPSIZEGRP> REFPOPSIZEGRPs { get; set; }
        public DbSet<REFPOSTEDSPEED> REFPOSTEDSPEEDs { get; set; }
        public DbSet<REFRECORDTYPE> REFRECORDTYPEs { get; set; }
        public DbSet<REFREPORTINGAGENCY> REFREPORTINGAGENCies { get; set; }
        public DbSet<REFRESTRAINT> REFRESTRAINTs { get; set; }
        public DbSet<REFROADALIGN> REFROADALIGNs { get; set; }
        public DbSet<REFROADCHARACTERISTIC> REFROADCHARACTERISTICS { get; set; }
        public DbSet<REFROADCONDITION> REFROADCONDITIONS { get; set; }
        public DbSet<REFROADDESIGN> REFROADDESIGNs { get; set; }
        public DbSet<REFROADGROUP> REFROADGROUPS { get; set; }
        public DbSet<REFROADTYPE> REFROADTYPEs { get; set; }
        public DbSet<REFROUTECODE> REFROUTECODES { get; set; }
        public DbSet<REFROUTECODESBK> REFROUTECODESBKs { get; set; }
        public DbSet<REFSCHOOLBUSRELATEDAR> REFSCHOOLBUSRELATEDARS { get; set; }
        public DbSet<REFSEATLOCATION> REFSEATLOCATIONs { get; set; }
        public DbSet<REFSEQUENCEOFEVENT> REFSEQUENCEOFEVENTS { get; set; }
        public DbSet<REFSEX> REFSEXes { get; set; }
        public DbSet<REFSHOULDER> REFSHOULDERs { get; set; }
        public DbSet<REFSOURCEOFCARRIERNAME> REFSOURCEOFCARRIERNAMEs { get; set; }
        public DbSet<REFSPECIALSYSTEM> REFSPECIALSYSTEMS { get; set; }
        public DbSet<REFSTATE> REFSTATEs { get; set; }
        public DbSet<REFSTATECLASS> REFSTATECLASSes { get; set; }
        public DbSet<REFSTDTABLESAM> REFSTDTABLESAMS { get; set; }
        public DbSet<REFSTDTABLESCR> REFSTDTABLESCRS { get; set; }
        public DbSet<REFSTREET> REFSTREETS { get; set; }
        public DbSet<REFSURFACECONDITION> REFSURFACECONDITIONs { get; set; }
        public DbSet<REFTA1FUNCGRPS> REFTA1FUNCGRPS { get; set; }
        public DbSet<REFTA1RELATEDDATA> REFTA1RELATEDDATA { get; set; }
        public DbSet<REFTOLLFACILITY> REFTOLLFACILITies { get; set; }
        public DbSet<REFTOWNCODE> REFTOWNCODEs { get; set; }
        public DbSet<REFTRAFFICSIGNAL> REFTRAFFICSIGNALS { get; set; }
        public DbSet<REFTRANSACTIONCODE> REFTRANSACTIONCODEs { get; set; }
        public DbSet<REFTRAVELRTCAT> REFTRAVELRTCATs { get; set; }
        public DbSet<REFTRAVELRTID> REFTRAVELRTIDs { get; set; }
        public DbSet<REFUNITTYPE> REFUNITTYPEs { get; set; }
        public DbSet<REFVEHCOLLIDEDWITH> REFVEHCOLLIDEDWITHs { get; set; }
        public DbSet<REFVEHCONFIGURATION> REFVEHCONFIGURATIONs { get; set; }
        public DbSet<REFVEHDAMAGECODE> REFVEHDAMAGECODEs { get; set; }
        public DbSet<REFVEHDAMAGEEST> REFVEHDAMAGEESTs { get; set; }
        public DbSet<REFVEHMAKE> REFVEHMAKEs { get; set; }
        public DbSet<REFVIOLATION> REFVIOLATIONS { get; set; }
        public DbSet<REFWEATHERCONDITION> REFWEATHERCONDITIONS { get; set; }
        public DbSet<REFWEIGHTUNIT> REFWEIGHTUNITS { get; set; }
    }
}
