//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRASHAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFLRSROUTEMILEAGE
    {
        public decimal ID { get; set; }
        public string ROUTENUMBER { get; set; }
        public string COUNTYTOWNCODE { get; set; }
        public string TOWN { get; set; }
        public Nullable<double> BEGINNING_MILEAGE { get; set; }
        public Nullable<double> ENDINGMILEAGE { get; set; }
        public Nullable<double> ACCUMMILEAGE { get; set; }
        public string DIRECTION { get; set; }
        public decimal PRINTUNKNOWNS { get; set; }
        public Nullable<System.DateTime> EFFECTIVEDATE { get; set; }
        public Nullable<double> ABEGINNING_MILEAGE { get; set; }
        public Nullable<double> AENDING_MILEAGE { get; set; }
        public Nullable<double> AACCUMMILEAGE { get; set; }
    }
}
