//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRASHAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFROUTECODESBK
    {
        public string ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> ROUTEORDER { get; set; }
        public Nullable<decimal> ROADGROUP { get; set; }
        public string LRSROUTEID { get; set; }
        public string MRD { get; set; }
    }
}
