//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRASHAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFSTREET
    {
        public decimal ID { get; set; }
        public string CITYCODE { get; set; }
        public string STREET1 { get; set; }
        public string STREET2 { get; set; }
    }
}
