//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRASHAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFTA1RELATEDDATA
    {
        public decimal ID { get; set; }
        public Nullable<double> THOUSANDSOFREGVEHICLES { get; set; }
        public Nullable<double> ANNUALMILESPERVEHICLE { get; set; }
        public Nullable<double> MOTORFUELGALLONSMILLIONS { get; set; }
        public Nullable<double> POPULATIONINTHOUSANDS { get; set; }
        public Nullable<double> LICDRIVERSINTHOUSANDS { get; set; }
        public Nullable<decimal> YEAROFDATAUSED { get; set; }
        public Nullable<double> NONFEDLOCALRURAL { get; set; }
        public Nullable<double> NONFEDERALLOCALURBAN { get; set; }
        public Nullable<double> NONFEDCOLLECTORRURAL { get; set; }
    }
}
