//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRASHAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFUNITTYPE
    {
        public decimal ID { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal NONMOTORVEHICLE { get; set; }
        public decimal COMMERCIAL { get; set; }
        public Nullable<decimal> PERSONTYPEEQUIVELENT { get; set; }
        public string COLLISIONNAME { get; set; }
        public Nullable<decimal> SORTORDER { get; set; }
        public Nullable<decimal> SHAPEID { get; set; }
    }
}
