//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRASHAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PQT_AccidentHeader
    {
        public string REPORTINGAGENCYid { get; set; }
        public string ReportingAgency { get; set; }
        public string REPORTNUMBER { get; set; }
        public decimal LOCALID { get; set; }
        public Nullable<System.DateTime> ACCIDENTTIME { get; set; }
        public System.DateTime ACCIDENTDATE { get; set; }
        public string STREETADDRESS { get; set; }
        public string TH_NUMBER { get; set; }
        public string VT_NUMBER { get; set; }
        public string US_NUMBER { get; set; }
        public string I_NUMBER { get; set; }
        public string INTERSECTIONWITH { get; set; }
        public string DISTANCEFROMNEARESTSTR { get; set; }
        public Nullable<decimal> DISTANCEFROMUNITS { get; set; }
        public Nullable<decimal> POSTEDSPEED { get; set; }
        public string DIRFROMNEARESTINTST { get; set; }
        public Nullable<decimal> DIROFCOLLISIONid { get; set; }
        public string DirOfCollision { get; set; }
        public string MILEMARKER1 { get; set; }
        public string MILEMARKER2 { get; set; }
        public string MILEMARKER3 { get; set; }
        public Nullable<decimal> AOTROADWAYGROUPid { get; set; }
        public string RoadGroup { get; set; }
        public Nullable<double> AOTACTUALMILEPOINT { get; set; }
        public Nullable<decimal> CRASHTYPEid { get; set; }
        public string CrashType { get; set; }
        public Nullable<decimal> TRAFFICSIGNALSid { get; set; }
        public string TrafficSignals { get; set; }
        public Nullable<decimal> WEATHERCONDITIONid { get; set; }
        public string WeatherCondition { get; set; }
        public Nullable<decimal> LIGHTid { get; set; }
        public string Light { get; set; }
        public Nullable<decimal> ROADCHARACTERISTICSid { get; set; }
        public string RoadCharacteristics { get; set; }
        public Nullable<decimal> ROADALIGNid { get; set; }
        public string RoadAlign { get; set; }
        public Nullable<decimal> ROADDESIGNid { get; set; }
        public string RoadDesign { get; set; }
        public Nullable<decimal> ROADTYPEid { get; set; }
        public string RoadType { get; set; }
        public Nullable<decimal> SURFACECONDITIONid { get; set; }
        public string SurfaceCondition { get; set; }
        public Nullable<decimal> ROADCONDITIONid { get; set; }
        public string RoadCondition { get; set; }
        public Nullable<decimal> OPERATORREPORTREQUIRED { get; set; }
        public Nullable<decimal> POLICEPHOTOVIDEOTAKEN { get; set; }
        public string AOTREPORTNUMBER { get; set; }
        public string EMSRUNNUMBER { get; set; }
        public string EMSAgencyid { get; set; }
        public string EMSAgency { get; set; }
        public string DESTINATIONHOSPITALid { get; set; }
        public string DestinationHopital { get; set; }
        public string EMSRUNNUMBER2 { get; set; }
        public string EMSAGENCY2id { get; set; }
        public string EMSAgency2 { get; set; }
        public string DESTINATIONHOSPITAL2id { get; set; }
        public string DestinationHopital2 { get; set; }
        public string DamageDescription { get; set; }
        public Nullable<bool> IsLocationChanged { get; set; }
        public Nullable<bool> NonReportable { get; set; }
        public string NonReportableAddress { get; set; }
        public string VCSG_CITYTOWN { get; set; }
        public string GIS_CITYTOWN { get; set; }
        public string VCSG_EASTING { get; set; }
        public string GIS_EASTING { get; set; }
        public string VCSG_NORTHING { get; set; }
        public string GIS_NORTHING { get; set; }
        public string VCSG_AOTROUTE { get; set; }
        public string GIS_AOTROUTE { get; set; }
        public string VCSG_LRSNUMBER { get; set; }
        public string GIS_LRSNUMBER { get; set; }
        public string VCSG_LATITUDE { get; set; }
        public string GIS_LATITUDE { get; set; }
        public string VCSG_LONGITUDE { get; set; }
        public string GIS_LONGITUDE { get; set; }
        public string HOWMAPPED { get; set; }
    }
}
