//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRASHAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PQT_Units
    {
        public string REPORTINGAGENCY { get; set; }
        public string REPORTNUMBER { get; set; }
        public decimal UNITID { get; set; }
        public string VEHNUMBER { get; set; }
        public Nullable<decimal> UNITTYPEid { get; set; }
        public string UnitType { get; set; }
        public string VEHREGPLATETYPE { get; set; }
        public string VEHREGSTATECODE { get; set; }
        public string VEHYEAR { get; set; }
        public Nullable<decimal> VEHMAKEid { get; set; }
        public string VehMake { get; set; }
        public string VEHMODEL { get; set; }
        public string ESTIMATEDSPEED { get; set; }
        public Nullable<decimal> DAMAGEESTIMATE { get; set; }
        public string DIRECTIONOFTRAVEL { get; set; }
        public string TOWEDBY { get; set; }
        public Nullable<decimal> VEHCOLLIDEDWITH { get; set; }
        public Nullable<decimal> ALCOHOLTESTid { get; set; }
        public string AlcoholTest { get; set; }
        public string ALCOHOLTESTRESULT { get; set; }
        public Nullable<decimal> DRUGTESTid { get; set; }
        public string DrugTestResult { get; set; }
        public Nullable<decimal> DRUGTESTRESULT1id { get; set; }
        public string DrugTestResult1 { get; set; }
        public Nullable<decimal> DRUGTESTRESULT2id { get; set; }
        public string DrugTestResult2 { get; set; }
        public Nullable<decimal> DEFECTIVEEQUIPMENT1 { get; set; }
        public Nullable<decimal> DEFECTIVEEQUIPMENT2 { get; set; }
        public Nullable<decimal> DEFECTIVEEQUIPMENT3 { get; set; }
        public Nullable<decimal> APPARENTOPERATORCOND1id { get; set; }
        public string ApparentOperatorCond1 { get; set; }
        public Nullable<decimal> APPARENTOPERATORCOND2id { get; set; }
        public string ApparentOperatorCond2 { get; set; }
        public Nullable<decimal> CONTRIBCIRCUMSTANCES1id { get; set; }
        public string ContribCircumstances1 { get; set; }
        public Nullable<decimal> CONTRIBCIRCUMSTANCES2id { get; set; }
        public string ContribCircumstances2 { get; set; }
        public string CITATIONTICKET1 { get; set; }
        public string CITATIONTICKET2 { get; set; }
        public string CITATIONTICKET3 { get; set; }
        public string VIOLATIONCODE1 { get; set; }
        public string VIOLATIONCODE2 { get; set; }
        public string VIOLATIONCODE3 { get; set; }
        public string EMSRUNNUMBER { get; set; }
        public string EMSAGENCYid { get; set; }
        public string EMSAgency { get; set; }
        public string DESTINATIONHOSPITALid { get; set; }
        public string DestinationHospital { get; set; }
        public string TRAILERYEAR { get; set; }
        public string TRAILERMAKE { get; set; }
        public string TRAILERMODEL { get; set; }
        public string TRAILERPLATENUMBER { get; set; }
        public string TRAILERSTATE { get; set; }
        public string SCHOOLBUSRELATEDARS { get; set; }
        public Nullable<decimal> UNOCCUPIED { get; set; }
        public Nullable<decimal> VehCollidedWith2 { get; set; }
        public Nullable<bool> TowedDueToDisablingDamage { get; set; }
        public Nullable<bool> CommercialVehicle { get; set; }
        public Nullable<bool> ATV { get; set; }
        public Nullable<bool> Snowmobile { get; set; }
        public Nullable<decimal> DRUGTESTRESULT3id { get; set; }
        public string DrugTestResult3 { get; set; }
        public Nullable<decimal> DRUGTESTRESULT4id { get; set; }
        public string DrugTestResult4 { get; set; }
        public Nullable<decimal> SEQUENCEOFEVENT1id { get; set; }
        public string SequenceOfEvents1 { get; set; }
        public Nullable<decimal> SEQUENCEOFEVENT2id { get; set; }
        public string SequenceOfEvents2 { get; set; }
        public Nullable<decimal> SEQUENCEOFEVENT3id { get; set; }
        public string SequenceOfEvents3 { get; set; }
        public Nullable<decimal> SEQUENCEOFEVENT4id { get; set; }
        public string SequenceOfEvents4 { get; set; }
        public Nullable<decimal> INTERSTCARRIER { get; set; }
        public string INTERSTCARRIERST { get; set; }
        public Nullable<decimal> SOURCE { get; set; }
        public Nullable<decimal> TOTALNUMOFAXLES { get; set; }
        public string GROSSVEHWTRATING { get; set; }
        public Nullable<decimal> GROSSVEHWTRATINGUNITSid { get; set; }
        public string GrossVehicleWeightUnit { get; set; }
        public string VEHICLELENGTH { get; set; }
        public Nullable<decimal> VEHICLELENGTHUNITSid { get; set; }
        public string VehicleLengthUnit { get; set; }
        public string TRAILORLENGTH { get; set; }
        public Nullable<decimal> TRAILORLENGTHUNITSid { get; set; }
        public string TrailerLenghtUnit { get; set; }
        public string TRAILORLICENSESTATE { get; set; }
        public Nullable<decimal> HAZMATPLACARD { get; set; }
        public Nullable<decimal> HAZMATSPILLED { get; set; }
        public string HAZMATCLASSNUM { get; set; }
        public Nullable<decimal> VEHCONFIGURATIONid { get; set; }
        public string VehicleConfiguration { get; set; }
        public Nullable<decimal> CARGOBODYTYPEid { get; set; }
        public string CargoBodyType { get; set; }
        public Nullable<decimal> Source2 { get; set; }
        public Nullable<decimal> Source3 { get; set; }
        public Nullable<decimal> Source4 { get; set; }
        public Nullable<short> GVWROrGCWRid { get; set; }
        public string GVWRorGCWR { get; set; }
        public Nullable<bool> IntraStCarrier { get; set; }
        public Nullable<bool> GovernmentCarrier { get; set; }
    }
}
